name: Command Sync Client
description: This works with Command Sync Server to run commands on the Velocity instance from the backend server.
author: windcolor-dev
main: ga.windpvp.commandsync.SyncPlugin
version: 0.0.1
commands:
  sync:
    description: "Syncs a command to the Velocity instance."